### PR TITLE
Feature/exo data line parser

### PR DESCRIPTION
**Pull request by evanShap**
mods to OrderedSeparatorLineParser and new Exo3DataLineParser class for Exo3 integration.
- Test app verifies the other user of the OrderedSeparatorLineParser (RBR parser) still works, including edge cases.
- Would love to get the test app into a unit test if someone wants to give me some pointers.
- @uma-kat - not yet integrated into your app, see the test app for usage example.

### CODE REVIEW

**Comment by matt001k** [comment]
@evanShap I definitely think that the test app you wrote would fit better as a unit test.
What do you need help on?
It seems you could drop your current test into the `test/src/common` directory and follow the guidelines [here](https://google.github.io/googletest/primer.html) to format the test correctly.
If you want to schedule some time, we can also just sit down and I can show you how the gtest operates and what needs to be done!

**Comment by evanShap** [comment]
> @evanShap I definitely think that the test app you wrote would fit better as a unit test. What do you need help on? It seems you could drop your current test into the `test/src/common` directory and follow the guidelines [here](https://google.github.io/googletest/primer.html) to format the test correctly. If you want to schedule some time, we can also just sit down and I can show you how the gtest operates and what needs to be done!

Thanks @matt001k! - can you point me towards example commands to cmake/build/run an individual test + all unit tests locally?

**Comment by matt001k** [comment]
@evanShap the cmake commands can be found in the `ENV_SETUP.md` file at the root of the repository!
The CMake command to setup the unit tests is:
`cmake -DCMAKE_BUILD_TYPE=TEST /relative/path/to/root/of/repository`
Following this command you can build the tests with either:

- `cmake --build .`
- `make`

Then to run the tests you invoke the command `ctest` in the build directory.
If you add `-V` as an argument to `ctest` you will get a verbose output.

If you want to invoke a single test you can run the individual executable from your unit test.
The following is how you could run this if you write your unit test in the `test/src/common` directory:
```
cd /path/to/build/directory
./test/src/common/{my_test_name_here}
```

**Comment by evanShap** [comment]
> @evanShap the cmake commands can be found in the `ENV_SETUP.md` file at the root of the repository! The CMake command to setup the unit tests is: `cmake -DCMAKE_BUILD_TYPE=TEST /relative/path/to/root/of/repository` Following this command you can build the tests with either:
> 
> * `cmake --build .`
> * `make`
> 
> Then to run the tests you invoke the command `ctest` in the build directory. If you add `-V` as an argument to `ctest` you will get a verbose output.
> 
> If you want to invoke a single test you can run the individual executable from your unit test. The following is how you could run this if you write your unit test in the `test/src/common` directory:
> 
> ```
> cd /path/to/build/directory
> ./test/src/common/{my_test_name_here}
> ```

**Comment by evanShap** [comment]
> @evanShap the cmake commands can be found in the `ENV_SETUP.md` file at the root of the repository! The CMake command to setup the unit tests is: `cmake -DCMAKE_BUILD_TYPE=TEST /relative/path/to/root/of/repository` Following this command you can build the tests with either:
> 
> * `cmake --build .`
> * `make`
> 
> Then to run the tests you invoke the command `ctest` in the build directory. If you add `-V` as an argument to `ctest` you will get a verbose output.
> 
> If you want to invoke a single test you can run the individual executable from your unit test. The following is how you could run this if you write your unit test in the `test/src/common` directory:
> 
> ```
> cd /path/to/build/directory
> ./test/src/common/{my_test_name_here}
> ```

Ah, I was looking in DEVELOPER.md - got the tests running, thanks!

**Comment by evanShap** [comment]
@matt001k - ChatGPT made short work of porting the manual test app to unit test suite. I added some additional comments to the ENV_SETUP readme - lmk if that all looks right.

**Review by matt001k — APPROVED** [review]
Code looks good!

**Comment by evanShap** [comment]
> Code looks good!

Though, it looks like the Github Action isn't actually running the unit tests - or am I missing something?

**Comment by matt001k** [comment]
@evanShap it should be ran in the python script `tools/.scripts/test/did_i_break_something.py` which is ran in the `run tests` step:
image

**Review by towynlin — APPROVED** [review]
👏

**Review by victorsowa12 — APPROVED** [review]

**Review by uma-kat — APPROVED** [review]

**Pull request merged**
